### ISSUE TITLE
Part Lengths

### ISSUE THREAD

**Issue by tomvdb** [yorkhackspace/meArm#2]
Hi There,

I've built a bigger version of the mearm and trying to implement the kinematics on it. I think I have most of it working, but struggling to get the sizes right. My part lengths are different than the original so I assume I need to modify these variables:

float L1=80; //Shoulder to elbow length
float L2=80; //Elbow to wrise length
float L3=68; //Length from wrist to hand PLUS base centre to shoulder

I'm slightly confused as to how exactly I need to measure the lengths, ie. where does this measure ment apply on the original mearm?

Are there pics available which shows these lengths on the regular mearm so that I can measure mine and adjust this?

Thanks,
T

**Comment by lexbailey** [comment]
I suspect these were measured from the centre of each pivot.

This should make the shoulder->elbow length and elbow->wrist length obvious.
I'm not so sure about L3.

Nick knows, he wrote the library, perhaps he'll reply too.

If you feel like being awesome, perhaps you could do this by having another
constructor override that lets you set these variable so that other people
can use different size arms without modifying the library code. Then submit
a pull request. :-) (and maybe fix that spelling error on "Elbow to wrise"
too)

Dan.

**Comment by aquila12** [comment]
Hi Tom,

I'll try to remember to put a picture together, but they're fairly simple
measurements.

L1 is just the length of the 'upper arm' (the bit from the rotating base to
the elbow), in mm.  It should be measured between the pivots along the
plastic part
L2 is the length of the 'lower arm' (from the elbow to the gripper), in
mm.  It should be measured between the pivots, along the plastic part.
L3 is the sum of two lengths (call them L3a, L3b).
L3a is the horizontal distance from the rotating base pivot point to the
centre of the shoulder axis.
L3b is the horizontal distance from the gripper's pivot point on the lower
arm to the centre of the gripper.

This really bad diagram might illustrate that poorly:
            x
     L1   /  \ L2
          /    \
         /      x--G
==|=x         L3b
      ^-- L3a

Regards

**Comment by tomvdb** [comment]
Thanks for the quick response guys. I'll see if I can make sense of it tonight on my original mearm, and then do the same on the bigger. I'll take some pics along the way. :)

> If you feel like being awesome, perhaps you could do this by having another
> constructor override that lets you set these variable so that other people
> can use different size arms without modifying the library code.

I can definitely do that 

Thanks for the help

**Comment by nishabe** [comment]
Hello team,
I am attaching an image depicting L1 and L2 based on my understanding. Please verify.

![arm2](https://cloud.githubusercontent.com/assets/5227686/11494729/1d0f3ccc-97ba-11e5-8b4c-a264fb9dacd7.jpg)

But I could not understand the concept of L3? Could you please explain more on it?
In the definition of L3a, I did not understand  'centre of shoulder axis'.
In the definition of L3b, I did not understand  'centre of gripper'.

**Comment by aquila12** [comment]
Just to provide a little background on L3's presence - the algorithm needs a point of reference (the origin) to refer to things with, which I chose to place directly above the axis the arm rotates around at the base - as this never moves.  Specifically, the point is directly above the base servo, at the same height as the shoulder servo.  From this point, there are four steps (vectors) to get to the gripper:
- Go forward to reach the shoulder (L3a)
- Follow the angle of the upper arm to get to the elbow (L1)
- Follow the angle of the forearm to get to the wrist (L2)
- Go forward to reach the front of the gripper (L3b)

Because the first and last steps are in the same direction, I chose to combine them, which might have made things a little confusing.  Here's a diagram that might help:
![mearm-geometry](https://cloud.githubusercontent.com/assets/6117158/11512378/b7a06b70-9865-11e5-8bb8-f9adf5963b04.png)

Your diagram for L1 and L2 is correct.  I've tried to illustrate L3a and L3b on the drawing - see below.  Both are easiest to understand if you look at the arm side-on, as L3 is accounting for extra horizontal distance in the assembly.
There are two rotations happening near the base - one horizontally, to swing the arm left and right (the base pivot axis) and one vertical, to lift and lower the arm (the shoulder pivot axis).  L3a is the front-to-back distance between these - basically, how far forward is the centre of the shoulder servo compared to the centre of the base servo.
At the wrist end, the algorithm has to account for the size of the gripper.  The two interesting points here are the wrist pivot axis (where the arm meets the horizontal "hand" part), and the point where the grips meet when they close (where they'd pick something up).  L3b is the distance between these - basically, how far forward is the point being gripped compared to the wrist.

![1d0f3ccc-97ba-11e5-8b4c-a264fb9dacd7](https://cloud.githubusercontent.com/assets/6117158/11508922/207223e0-9853-11e5-9ac8-e028037a1891.jpg)

I hope that explains it a bit better.

**Comment by nishabe** [comment]
Nick, your explanation is super clear and simple. 
The description could not have been better.
Thank you so much!
Note: Noticed a minor issue in your diagram. Looks like you interchanged the text 'L3a' and 'L3b'.  
(Not a big deal. Anyone who read your reply can figure it out.)

**Comment by aquila12** [comment]
Excellent - thanks for the feedback (and for spotting the error - I've edited the comment to fix it now).

Cheers!

**Comment by nishabe** [comment]
Hello Nick,

The first phase of my project has been completed. Thank you very much for
your help.
The merArm library plays one of the most important role in this pet project.
Please find the details of it here:
https://nishabe.wordpress.com/2016/01/25/a-robotic-arm-integrated-with-calabash-2/
.
Thanks again!
- Aneesh
